Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Grab the 5 systems with the lowest energy
configs_for_dft = df.sort_values(by = "relaxed_energy_ml").relaxed_atoms.tolist()[0:5]
config_idxs = df.sort_values(by = "relaxed_energy_ml").relaxation_idx.tolist()[0:5]

# Write the inputs
for idx, config in enumerate(configs_for_dft):
    os.mkdir(f"data/{config_idxs[idx]}")
    write_vasp_input_files(config, outdir = f"data/{config_idxs[idx]}/")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[13], line 8[0m
[1;32m      6[0m [38;5;28;01mfor[39;00m idx, config [38;5;129;01min[39;00m [38;5;28menumerate[39m(configs_for_dft):
[1;32m      7[0m     os[38;5;241m.[39mmkdir([38;5;124mf[39m[38;5;124m"[39m[38;5;124mdata/[39m[38;5;132;01m{[39;00mconfig_idxs[idx][38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m----> 8[0m     [43mwrite_vasp_input_files[49m[43m([49m[43mconfig[49m[43m,[49m[43m [49m[43moutdir[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;124;43mdata/[39;49m[38;5;132;43;01m{[39;49;00m[43mconfig_idxs[49m[43m[[49m[43midx[49m[43m][49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m/[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/ocdata/utils/vasp.py:124[0m, in [0;36mwrite_vasp_input_files[0;34m(atoms, outdir, vasp_flags)[0m
[1;32m    122[0m atoms, vasp_flags [38;5;241m=[39m _clean_up_inputs(atoms, vasp_flags[38;5;241m.[39mcopy())
[1;32m    123[0m calc [38;5;241m=[39m Vasp(directory[38;5;241m=[39moutdir, [38;5;241m*[39m[38;5;241m*[39mvasp_flags)
[0;32m--> 124[0m [43mcalc[49m[38;5;241;43m.[39;49m[43mwrite_input[49m[43m([49m[43matoms[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/ase/calculators/vasp/vasp.py:471[0m, in [0;36mVasp.write_input[0;34m(self, atoms, properties, system_changes)[0m
[1;32m    468[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mdirectory [38;5;241m!=[39m os[38;5;241m.[39mcurdir [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39misdir([38;5;28mself[39m[38;5;241m.[39mdirectory):
[1;32m    469[0m     os[38;5;241m.[39mmakedirs([38;5;28mself[39m[38;5;241m.[39mdirectory)
[0;32m--> 471[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43minitialize[49m[43m([49m[43matoms[49m[43m)[49m
[1;32m    473[0m GenerateVaspInput[38;5;241m.[39mwrite_input([38;5;28mself[39m, atoms, directory[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mdirectory)

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/ase/calculators/vasp/create_input.py:1301[0m, in [0;36mGenerateVaspInput.initialize[0;34m(self, atoms)[0m
[1;32m   1298[0m     [38;5;28mself[39m[38;5;241m.[39msymbol_count[38;5;241m.[39mappend([m, symbolcount[m]])
[1;32m   1300[0m [38;5;66;03m# create pseudopotential list[39;00m
[0;32m-> 1301[0m [38;5;28mself[39m[38;5;241m.[39mppp_list [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_build_pp_list[49m[43m([49m[43matoms[49m[43m,[49m
[1;32m   1302[0m [43m                                    [49m[43msetups[49m[38;5;241;43m=[39;49m[43msetups[49m[43m,[49m
[1;32m   1303[0m [43m                                    [49m[43mspecial_setups[49m[38;5;241;43m=[39;49m[43mspecial_setups[49m[43m)[49m
[1;32m   1305[0m [38;5;28mself[39m[38;5;241m.[39mconverged [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m   1306[0m [38;5;28mself[39m[38;5;241m.[39msetups_changed [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/ase/calculators/vasp/create_input.py:1204[0m, in [0;36mGenerateVaspInput._build_pp_list[0;34m(self, atoms, setups, special_setups)[0m
[1;32m   1196[0m     [38;5;28;01melse[39;00m:
[1;32m   1197[0m         msg [38;5;241m=[39m ([38;5;124m"""[39m[38;5;124mLooking for PP for [39m[38;5;132;01m{}[39;00m
[1;32m   1198[0m [38;5;124m                The pseudopotentials are expected to be in:[39m
[1;32m   1199[0m [38;5;124m                LDA:  $VASP_PP_PATH/potpaw/[39m
[0;32m   (...)[0m
[1;32m   1202[0m [38;5;124m                [39m
[1;32m   1203[0m [38;5;124m                No pseudopotential for [39m[38;5;132;01m{}[39;00m[38;5;124m![39m[38;5;124m"""[39m[38;5;241m.[39mformat(potcar, symbol))
[0;32m-> 1204[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(msg)
[1;32m   1205[0m [38;5;28;01mreturn[39;00m ppp_list

[0;31mRuntimeError[0m: Looking for PP for potpaw_PBE/Cu/POTCAR
                        The pseudopotentials are expected to be in:
                        LDA:  $VASP_PP_PATH/potpaw/
                        PBE:  $VASP_PP_PATH/potpaw_PBE/
                        PW91: $VASP_PP_PATH/potpaw_GGA/
                        
                        No pseudopotential for Cu!

