Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# If you run the above cell -- dont run this one
fmax = 0.05 # [eV / ang**2]
delta_fmax_climb = 0.4
neb = OCPNEB(
    frame_sets[0],
    checkpoint_path=checkpoint_path,
    k=1,
    batch_size=8,
    cpu = cpu,
)
optimizer = BFGS(
    neb,
    trajectory=f"ch_dissoc_on_Ru_0.traj",
)
conv = optimizer.run(fmax=fmax + delta_fmax_climb, steps=200)
if conv:
    neb.climb = True
    conv = optimizer.run(fmax=fmax, steps=300)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[7], line 5[0m
[1;32m      2[0m fmax [38;5;241m=[39m [38;5;241m0.05[39m [38;5;66;03m# [eV / ang**2][39;00m
[1;32m      3[0m delta_fmax_climb [38;5;241m=[39m [38;5;241m0.4[39m
[1;32m      4[0m neb [38;5;241m=[39m OCPNEB(
[0;32m----> 5[0m     [43mframe_sets[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m,
[1;32m      6[0m     checkpoint_path[38;5;241m=[39mcheckpoint_path,
[1;32m      7[0m     k[38;5;241m=[39m[38;5;241m1[39m,
[1;32m      8[0m     batch_size[38;5;241m=[39m[38;5;241m8[39m,
[1;32m      9[0m     cpu [38;5;241m=[39m cpu,
[1;32m     10[0m )
[1;32m     11[0m optimizer [38;5;241m=[39m BFGS(
[1;32m     12[0m     neb,
[1;32m     13[0m     trajectory[38;5;241m=[39m[38;5;124mf[39m[38;5;124m"[39m[38;5;124mch_dissoc_on_Ru_0.traj[39m[38;5;124m"[39m,
[1;32m     14[0m )
[1;32m     15[0m conv [38;5;241m=[39m optimizer[38;5;241m.[39mrun(fmax[38;5;241m=[39mfmax [38;5;241m+[39m delta_fmax_climb, steps[38;5;241m=[39m[38;5;241m200[39m)

[0;31mIndexError[0m: list index out of range

